SEED: 42
MODEL:
  name: alexnet
  num_classes: 10
  kwargs:
    num_classes: 10
    use_lrn: true
    overlap_pool: true
    dropout_p: 0.5
    init_bias_ones: true
    width_mult: 1.0
DATA:
  engine: hf_imagefolder
  # 官方镜像（如）："frgfm/imagenette" 可能提供 splits: train/validation
  hf_name_or_dir: frgfm/imagenette
  train_dir: ./data/imagenette
  img_size: 224
  workers: 4
AUG:
  lighting: true
  lighting_std: 0.1
  hflip_p: 0.5
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]
  warp_square_256: false
TRAIN:
  epochs: 20
  batch_size: 128
  lr: 0.01
  weight_decay: 0.0005
  optimizer:
    name: sgd
  scheduler:
    name: multistep
    milestones: [8, 14, 18]
    gamma: 0.1
  amp: true
  grad_clip: 0.0
EVAL:
  ten_crop: false
OUTPUT:
  log_dir: runs/imagenette/logs
  tb_dir: runs/imagenette/tb
  ckpt_dir: runs/imagenette/ckpts
